---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx1-lb
  name: nginx1-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80 
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    name: nginx1

