---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    name: nginx1
spec:
  restartPolicy: Always
  containers:
  - image: ajnouri/nginx
    name: nginx1
    ports:
    - containerPort: 80
      name: web
    volumeMounts:
      - name: nginx-persistent
        mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-persistent
    gcePersistentDisk:
      pdName: disk2
      fsType: ext4

