---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sshfsserver
  name: sshfsserver
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
  selector:
    name: sshfsserver

